language: node_js
node_js:
- '0.11'
- '0.10'
before_script:
 - chmod +x ./node_modules/.bin/mocha
 - chmod +x ./node_modules/mocha/bin/_mocha
 - chmod +x ./node_modules/.bin/istanbul
notifications:
  email:
    recipients:
      - smrycek@ncsu.edu
      - ldshehan@ncsu.edu
      - shpatel5@ncsu.edu
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key: 7b1fcf62-bf4b-4f5f-88d2-a282c5050456
  app: on-call-escalation-manager