language: node_js
node_js:
- '0.11'
- '0.10'
before_script:
 - chmod +x ./node_modules/.bin/mocha
 - chmod +x ./node_modules/mocha/bin/_mocha
 - chmod +x ./node_modules/.bin/istanbul
notifications:
  email:
    recipients:
      - bdill@bandwidth.com
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key: 7aaf754d-8d92-4c03-80a1-e79456c8f243
  app: on-call-escalation-manager